<?php
/**
 * Created by PhpStorm.
 * User: suhomlinov_m
 * Date: 14.06.17
 * Time: 10:41
 */
namespace app\components;

use PHPExcel;
use PHPExcel_Exception;
use PHPExcel_IOFactory;
//use yii\base\Component;

class XlsxParserComponent extends \yii\base\Component
{

    public $xlsx;
    public $errorMsg;
    public $status;


    /**
     * Инициализация переменных
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->errorMsg = "none";
        $this->xlsx = new PHPExcel();
        $this->status = false;
    }
//    function __construct()
//    {
//        $this->errorMsg = "none";
//        $this->xlsx = new PHPExcel();
//        $this->status = false;
//    }

    /**
     * Загрузка и открытие xlsx файлов
     * @param $path
     * @return bool|\PHPExcel
     */
    public function openXlsx ($path)
    {
        try {
            $this->xlsx = PHPExcel_IOFactory::load($path);
            $this->status = true;
        } catch (PHPExcel_Exception $e) {
            $this->errorMsg = $e->getMessage();
            $this->status = false;
            return null;
        }
        return true;
    }

    /**
     * Получение значения указанной ячейки, начиная с 0
     * @param $s - лист
     * @param $r - строка
     * @param $c - ячейка
     * @return mixed|null
     */
    public function getCellValue ($s, $r, $c)
    {
        $r++;
        if (is_object($this->xlsx)) {
            $sheet = $this->xlsx->getSheet($s);
            $cell = $sheet->getCellByColumnAndRow($c, $r);
            $this->status = true;
            return $cell->getValue();
        } else {
            $this->errorMsg = "Не открыт .xlsx файл";
            $this->status = false;
            return null;
        }
    }

    /**
     * Получение количества строк на указанном листе
     * @param $s -
     * @return mixed
     */
    public function rowCount ($s)
    {
        $sheet = $this->xlsx->getSheet($s);
        return $sheet->getHighestRow();
    }

}